---
- name: Instalar OCS Inventory Agent no Windows
  hosts: windows
  tasks:
    - name: Garantir que a pasta C:\temp exista
      win_file:
        path: C:\temp
        state: directory

    - name: Copiar o instalador do OCS Inventory Agent para o host
      win_copy:
        src: /home/ronaldo/TI/Softwares/Script_OCS/ocs.exe
        dest: C:\temp\ocs.exe

    - name: Instalar o OCS Inventory Agent
      win_command: 'C:\temp\ocs.exe /server=http://192.168.0.252/ocsinventory /tag={{ ansible_hostname }} /debug=1 /s /nosplash'
      args:
        chdir: C:\temp

    - name: Limpar o arquivo de instalação
      win_file:
        path: C:\temp\ocs.exe
        state: absent

    - name: Limpar o arquivo log de instalação
      win_file:
        path: C:\temp\OCS-Windows-Agent-Setup-x64.log
        state: absent

    - name: Exibir data e hora do término da instalação
      debug:
        msg: "Instalação do OCS Inventory Agent concluída: Data: {{ ansible_date_time.date }} - Hora: {{ ansible_date_time.time }}"