---
- name: Reiniciar o Arcserve
  hosts: windows
  tasks:
    - name: Garantir que a pasta C:\temp exista
      win_file:
        path: C:\temp
        state: directory

    - name: Copiar o arquivo MSI para o servidor
      win_copy:
        src: /home/ronaldo/TI/Script/reinicia_arcserve.ps1
        dest: C:\temp\

    - name: Executar o script .bat
      win_command: C:\temp\reiniciar_processo.bat

    - name: Limpar o arquivo log de instalação
      win_file:
        path: C:\temp\reiniciar_processo.bat
        state: absent