---
- name: Instalar TeamViewer QuickSupport
  hosts: windows
  tasks:
    - name: Copiar o portable do TeamViewer QuickSupport
      win_copy:
        src: /home/ronaldo/TI/Softwares/TeamViewerQS/TeamViewerQS_x64.exe
        dest: C:\TeamViewerQS\
    - name: Criar atalho para TeamViewer Quick Support no Desktop
      win_shell: |
        $teamViewerPath = "C:\TeamViewerQS\TeamViewerQS_x64.exe"
        $shortcutLocation = [System.Environment]::GetFolderPath('Desktop')
        $shortcutName = "TeamViewer Quick Support.lnk"
        $WshShell = New-Object -ComObject WScript.Shell
        $Shortcut = $WshShell.CreateShortcut("$shortcutLocation\$shortcutName")
        $Shortcut.TargetPath = $teamViewerPath
        $Shortcut.Save()
        Write-Host "Atalho do TeamViewer Quick Support criado com sucesso em $shortcutLocation\$shortcutName."