- name: Testar conexão com Windows
  hosts: windows
  vars:
    ansible_connection: winrm
    ansible_port: 5985  # ou 5985 para HTTP
    ansible_user: administrator
    ansible_password: ZNjzu$9#mVWht6L
    ansible_winrm_server_cert_validation: ignore  # se estiver usando HTTPS e o certificado não for válido
  tasks:
    - name: Verificar conectividade
      win_ping:
