---
- name: Instalar e configurar software em servidores Windows
  hosts: windows
  tasks:
    - name: Garantir que a pasta C:\temp exista
      win_file:
        path: C:\temp
        state: directory

    - name: Copiar o arquivo MSI para o servidor
      win_copy:
        src: /home/ronaldo/TI/Softwares/VisualStudio/visualstudio.ps1
        dest: C:\temp\

    - name: Instalar o MSI
      win_shell:  |
        powershell.exe -ExecutionPolicy Bypass -File C:\temp\visualstudio.ps1

    - name: Limpar o arquivo log de instalação
      win_file:
        path: C:\temp\visualstudio.ps1
        state: absent