[docker]
#localhost ansible_connection=local

[windows]
#deskbancada1
#lcadiguni
#mletti
#dgermano
#jcapelao


[windows:vars]
ansible_user=gvdasa\administrador
ansible_password=&UADE68=@!=#$
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_port=5985
