
[windows]
#SRVTESTEAUTO
#SRVARCCONSOLE
#SRVAPOIOTI
#GVBUILD
#SRVA87
#SRVAD3
#SRVAPI
#SRVCENTRIS
#SRVCENTRISDEV
#SRVCONSULTORIA
#SRVGESTAOCONTAS
#SRVMOBILE
#SRVMOBILE2
#SRVMOBILEHML
#SRVDIRETORIO
#SRVNPAPP
#GVSETUP ansible_host=192.168.16.184
#SRVDP6-2
#SRVBACKUP
#GVSERVERDB
#GVSERVERDB2
#TSMETA
#SRVAD2
#GVSERVERDB3
#SRVDP62
#SRVTS
#OPTIMUSPRIME
#SRVBACKUPCORP
#SRVBACKUP2
#SRVGVMERCADO
#SRVPERGAMUM
#SRVSENACHML
#GVSERVERDBTEMP
#SRVWEB
#SRVQAEVOWEB
#SRVPONTECOLLEGE
#SRVRADAR
#SRVSQLPROD
#SYSTEMCENTERCM
#GVBUILD1
#SRVQUALITOR810
#ZEUS
#SRVVERSION





[windows:vars]
ansible_user=gvdasa\administrador
ansible_password=&UADE68=@!=#$
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_port=5985
