---
- name: Executar instalação de .exe com .xml
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Copiar o arquivo .exe para o Windows
      ansible.windows.win_copy:
        src: /home/ronaldo/TI/Softwares/Bitdefender/epskit_x64.exe
        dest: C:\temp\epskit_x64.exe

    - name: Copiar o arquivo .xml para o Windows
      ansible.windows.win_copy:
        src: /home/ronaldo/TI/Softwares/Bitdefender/installer.xml
        dest: C:\temp\installer.xml

    - name: Executar o arquivo .exe com o .xml como argumento
      ansible.windows.win_command:
        cmd: C:\temp\epskit_x64.exe /config=C:\temp\installer.xml

    - name: Limpar o arquivo de instalação
      win_file:
        path: C:\temp\epskit_x64.exe
        state: absent

    - name: Limpar o arquivo XML de instalação
      win_file:
        path: C:\temp\installer.xml
        state: absent
