---
- name: Instalar e configurar software em servidores Windows
  hosts: windows
  tasks:
    - name: Garantir que a pasta C:\temp exista
      win_file:
        path: C:\temp
        state: directory

    - name: Copiar o arquivo MSI para o servidor
      win_copy:
        src: /home/ronaldo/TI/Softwares/checkmk/check_mk_agent.msi
        dest: C:\temp\check_mk_agent.msi

    - name: Instalar o MSI
      win_package:
        path: 'C:\temp\check_mk_agent.msi'
        state: present
        wait_for_children: yes

    - name: Copiar o arquivo IIS Pool State para o servidor
      win_copy:
        src: /home/ronaldo/TI/Softwares/checkmk/iis_app_pool_state.ps1
        dest: C:\Program Files (x86)\checkmk\service\plugins

    - name: Copiar o arquivo Veem Status para o servidor
      win_copy:
        src: /home/ronaldo/TI/Softwares/checkmk/veeam_backup_status.ps1
        dest: C:\Program Files (x86)\checkmk\service\plugins\

    - name: Copiar o arquivo Win_license para o servidor
      win_copy:
        src: /home/ronaldo/TI/Softwares/checkmk/win_license.bat
        dest: C:\Program Files (x86)\checkmk\service\plugins

    - name: Remover os arquivos temporários após as instalações
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\temp\check_mk_agent.msi