---
- name: Playbook para configurar Setor College/Centris/NAP
  hosts: windows
  tasks:
    # Aqui você pode colocar outras tarefas específicas, se necessário

# Importando os playbooks externos após a definição do playbook principal
- import_playbook: install_chocolatey.yml
- import_playbook: ocs-playbook.yml
- import_playbook: instaladores_padrao-playbook.yml
- import_playbook: iis-playbook.yml
- import_playbook: microsoft_teams-playbook.yml
- import_playbook: teamviewerqs-playbook.yml
- import_playbook: desenvolvimento-playbook.yml
- import_playbook: visualstudio-playbook.yml