---
- name: Instalar ferramentas de desenvolvimento
  hosts: windows
  tasks:
    - name: Instalar Git
      win_chocolatey:
        name: git
        state: present

    - name: Instalar Visual Studio 2019
      win_chocolatey:
        name: visualstudio2019enterprise
        state: present
        package_params: '--locale en-US --add Microsoft.VisualStudio.Workload.Data;includeRecommended --add Microsoft.VisualStudio.Workload.NetWeb;includeRecommended'

    - name: Instalar VSCode
      win_chocolatey:
        name: vscode
        state: present

    - name: Instalar Postman
      win_chocolatey:
        name: postman
        state: present

    - name: Instalar .NET Framework 4.8 SDK
      win_chocolatey:
        name: netfx-4.8-devpack
        state: present

    - name: Instalar Azure Copy
      win_chocolatey:
        name: azcopy
        state: present

    - name: Instalar jdk8
      win_chocolatey:
        name: jdk8
        state: present

    - name: Instalar java
      win_chocolatey:
        name: javaruntime
        state: present

    - name: Instalar Node.js LTS
      win_chocolatey:
        name: nodejs-lts
        state: present

    - name: Baixar Sencha CMD
      win_get_url:
        url: http://cdn.sencha.com/cmd/7.3.0.19/no-jre/SenchaCmd-7.3.0.19-windows-x32-no_jre.exe
        dest: C:\Temp\SenchaCmd.exe

    - name: Instalar Sencha CMD
      win_command:
        cmd: C:\Temp\SenchaCmd.exe -q


