---
- name: Instalar Microsoft Teams
  hosts: windows
  tasks:
    - name: Copiar o instalador do Microsoft Teams
      win_copy:
        src: /home/ronaldo/TI/Softwares/Microsoft/Teams/Teams_windows_x64.msi
        dest: C:\temp\

    - name: Instalar o Microsoft Teams
      win_package:
        path: 'C:\temp\Teams_windows_x64.msi'
        state: present
        wait_for_children: yes

    - name: Limpar o arquivo de instalação
      win_file:
        path: C:\temp\Teams_windows_x64.msi
        state: absent
