---
- name: Instalar ferramentas de desenvolvimento e mobile
  hosts: windows
  tasks:

    # Instalar ferramentas mobile
    - name: Instalar Android Studio
      win_chocolatey:
        name: androidstudio
        state: present

    - name: Instalar ImageMagick
      win_chocolatey:
        name: imagemagick
        state: present

    - name: Instalar Inno Setup
      win_chocolatey:
        name: innosetup
        state: present

    - name: Instalar VNC Viewer
      win_chocolatey:
        name: vnc-viewer
        state: present

    - name: Instalar Microsoft Azure Storage Explorer
      win_chocolatey:
        name: microsoftazurestorageexplorer
        state: present

    - name: Instalar Nodist
      win_chocolatey:
        name: nodist
        state: present

    - name: Instalar OpenSSL
      win_chocolatey:
        name: openssl
        state: present

    # Instalar ferramentas de desenvolvimento
    - name: Instalar Git
      win_chocolatey:
        name: git
        state: present

    - name: Instalar Visual Studio 2017
      win_chocolatey:
        name: visualstudio2017enterprise
        state: present
        package_params: "--locale 'En-us' --package-parameters '--add Microsoft.VisualStudio.Workload.Data;includeRecommended --add Microsoft.VisualStudio.Workload.NetWeb;includeRecommended'"

    - name: Instalar VSCode
      win_chocolatey:
        name: vscode
        state: present

    - name: Instalar Postman
      win_chocolatey:
        name: postman
        state: present

    - name: Instalar .NET Framework 4.8 SDK
      win_chocolatey:
        name: netfx-4.8-devpack
        state: present

    - name: Instalar Azure Copy
      win_chocolatey:
        name: azcopy
        state: present

    - name: Instalar JDK 8
      win_chocolatey:
        name: jdk8
        state: present

    - name: Instalar Java Runtime
      win_chocolatey:
        name: javaruntime
        state: present

    - name: Instalar Node.js LTS
      win_chocolatey:
        name: nodejs-lts
        state: present

    # Download e instalar Sencha CMD
    - name: Baixar Sencha CMD
      win_get_url:
        url: http://cdn.sencha.com/cmd/7.3.0.19/no-jre/SenchaCmd-7.3.0.19-windows-x32-no_jre.exe
        dest: C:\Temp\SenchaCmd.exe

    - name: Instalar Sencha CMD
      win_command:
        cmd: C:\Temp\SenchaCmd.exe -q
