---
- name: Instalar TeamViewer host
  hosts: windows
  tasks:
    - name: Copiar o instalador do TeamViewer host
      win_copy:
        src: /home/ronaldo/TI/Softwares/TeamViewerQS/TeamViewer_Host_Setup.exe 
        dest: C:\temp\

    - name: Instalar o TeamViewer host
      win_package:
        path: 'C:\temp\TeamViewer_Host_Setup.exe'
        state: present
        wait_for_children: yes

    - name: Limpar o arquivo de instalação
      win_file:
        path: C:\temp\TeamViewer_Host_Setup.exe
        state: absent
