---
- name: Instalar VMware Tools em uma máquina Windows
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Instalar VMware Tools
      win_chocolatey:
        name: vmware-tools
        version: '12.0.6.20104755'
        state: present
